
export enum AuthSignUp{
  AUTH_SIGN_UP_REQUEST = 'AUTH_SIGN_UP_REQUEST',
  AUTH_SIGN_UP_SUCCESS= 'AUTH_SIGN_UP_SUCCESS',
  AUTH_SIGN_UP_FAIL = 'AUTH_SIGN_UP_FAIL',
}

export enum AuthSignIn{
  AUTH_SIGN_IN_REQUEST = 'AUTH_SIGN_IN_REQUEST',
  AUTH_SIGN_IN_SUCCESS = 'AUTH_SIGN_IN_SUCCESS',
  AUTH_SIGN_IN_FAIL = 'AUTH_SIGN_IN_FAIL',
}

export enum AuthSignOut{
  AUTH_SIGN_OUT_REQUEST= 'AUTH_SIGN_OUT_REQUEST',
  AUTH_SIGN_OUT_SUCCESS= 'AUTH_SIGN_OUT_SUCCESS',
  AUTH_SIGN_OUT_FAIL= 'AUTH_SIGN_OUT_FAIL',
  AUTH_SIGN_OUT_CLEAR= 'AUTH_SIGN_OUT_CLEAR',
}