
export enum AddCategory{
  ADD_CATEGORY_REQUEST= 'ADD_CATEGORY_REQUEST',
  ADD_CATEGORY_SUCCESS= 'ADD_CATEGORY_SUCCESS',
  ADD_CATEGORY_FAIL= 'ADD_CATEGORY_FAIL'
}

export enum GetCategory{
  GET_CATEGORY_REQUEST= 'GET_CATEGORY_REQUEST',
  GET_CATEGORY_SUCCESS= 'GET_CATEGORY_SUCCESS',
  GET_CATEGORY_FAIL= 'GET_CATEGORY_FAIL'
}

export enum EditCategory{
  EDIT_CATEGORY_REQUEST = 'EDIT_CATEGORY_REQUEST',
  EDIT_CATEGORY_SUCCESS= 'EDIT_CATEGORY_SUCCESS',
  EDIT_CATEGORY_FAIL= 'EDIT_CATEGORY_FAIL'
}

export enum DeleteCategory{
  DELETE_CATEGORY_REQUEST= 'DELETE_CATEGORY_REQUEST',
  DELETE_CATEGORY_SUCCESS= 'DELETE_CATEGORY_SUCCESS',
  DELETE_CATEGORY_FAIL= 'DELETE_CATEGORY_FAIL'
}

export enum SearchCategory{
  SEARCH_CATEGORY_REQUEST= 'SEARCH_CATEGORY_REQUEST',
  SEARCH_CATEGORY_SUCCESS= 'SEARCH_CATEGORY_SUCCESS',
  SEARCH_CATEGORY_FAIL= 'SEARCH_CATEGORY_FAIL'
}


export enum AddContent{
  ADD_CONTENT_REQUEST= 'ADD_CONTENT_REQUEST',
  ADD_CONTENT_SUCCESS= 'ADD_CONTENT_SUCCESS',
  ADD_CONTENT_FAIL= 'ADD_CONTENT_FAIL'
}

export enum GetContent{
  GET_CONTENT_REQUEST= 'GET_CONTENT_REQUEST',
  GET_CONTENT_SUCCESS= 'GET_CONTENT_SUCCESS',
  GET_CONTENT_FAIL= 'GET_CONTENT_FAIL'
}

export enum EditContent{
  EDIT_CONTENT_REQUEST= 'EDIT_CONTENT_REQUEST',
  EDIT_CONTENT_SUCCESS= 'EDIT_CONTENT_SUCCESS',
  EDIT_CONTENT_FAIL= 'EDIT_CONTENT_FAIL'
}

export enum DeleteContent{
  DELETE_CONTENT_REQUEST= 'DELETE_CONTENT_REQUEST',
  DELETE_CONTENT_SUCCESS= 'DELETE_CONTENT_SUCCESS',
  DELETE_CONTENT_FAIL= 'DELETE_CONTENT_FAIL'
}

export enum SearchContent{
  SEARCH_CONTENT_REQUEST= 'SEARCH_CONTENT_REQUEST',
  SEARCH_CONTENT_SUCCESS= 'SEARCH_CONTENT_SUCCESS',
  SEARCH_CONTENT_FAIL= 'SEARCH_CONTENT_FAIL',
}